### ISSUE TITLE
time-boxed effort to improve VSCode integration

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-python#281]
Several devs left comments during bug bash about VSCode not doing auto-imports, needing to re-load to get the docs to show up, etc.  Experiment to see if there are things we need to add, or if there are specific VSCode settings we should recommend that users enable, etc.

**Comment by malandis** [comment]
1. The language server used by default is pylance. This uses the Microsoft type checker pyright.
2. In VS Code, pylance by default only indexes top level third-party packages for auto-import, analysis, and autocompletion. This means by default no help from `from momento.responses import ...` because those are second level names.
3. Another issue is pyright considers names private by default unless in `__all__` or unless using a redundant alias. See here https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface. I will update the APIs to use `__all__`

**Comment by malandis** [comment]
Relevant settings in VS Code. Under extensions -> pylance

![image](https://user-images.githubusercontent.com/3690240/221285389-681e6e62-966a-4abf-8770-1a69d0149227.png)
Other settings to adjust:
![image](https://user-images.githubusercontent.com/3690240/221285724-3b1f35df-0e76-4fef-a8a3-c3ee38b51b88.png)
