### ISSUE TITLE
type inference for client object not working with `async with` - determine root cause

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-python#285]
Michael reported that using an `async with ... as` clause in VSCode, the editor was not inferring the type of the CacheClient.  That would be a pretty big deal for VSCode users.

We should try this in IDEA/PyCharm to narrow down the cause; if it works there then we can maybe rule out it being a library issue, and assume that it is something VSCode specific.

Either way, if we can't get it working in VSCode we may want to update our example code to account for this (e.g. don't use `async with`, just do a normal variable assignment and then an explicit close/exit?  Or see if you can add a mypy type hint after the `as` clause?

**Comment by malandis** [comment]
The root cause is import visibility rules used by pylance. See here https://github.com/momentohq/client-sdk-python/issues/281#issuecomment-1444425023.

This possibly explains the issue seen in IntelliJ with the match statements as well. To fix I will apply both redundant type aliases in `__init__` files and also specify `__all__`. The `__all__` specifications will allow users to type `from momento.responses import *`. Though this is discouraged by python, some users may expect it, and it also makes the names public.

**Comment by malandis** [comment]
related: https://github.com/momentohq/client-sdk-python/issues/296
